# Generated by Django 4.2.3 on 2023-08-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolos',
            options={'verbose_name_plural': 'Bolos'},
        ),
        migrations.AlterModelOptions(
            name='doces',
            options={'verbose_name_plural': 'Doces'},
        ),
        migrations.AlterModelOptions(
            name='macarons',
            options={'verbose_name_plural': 'Macarons'},
        ),
        migrations.AlterModelOptions(
            name='sabor',
            options={'verbose_name_plural': 'Sabores'},
        ),
    ]
